### ISSUE TITLE
discord server for lolsite project

### ISSUE THREAD

**Issue by trangtiu** [brianjp93/lolsite-fe#6]
Hi @brianjp93 @
I hope this message finds you well. I recently came across the "lolsite-fe & lolsite" project on GitHub and am interested in learning more about it 

I was wondering if there is an official Discord server or group for the project where communicate, ask questions

Thank you for your time and consideration.Tks

**Comment by brianjp93** [comment]
Hi @trangtiu,
There is no such discord server currently, but I would consider opening one up with there was enough interest and some people contributing to the project.  For now the only mode of communication is through github.

**Comment by trangtiu** [comment]
Can I contact you via another channel like Telegram, Skype or Discord?

**Comment by brianjp93** [comment]
@trangtiu This is a channel that I have for league related things, but not the website specifically.  Let's talk there
https://discord.gg/GmKk4Ph6
